language: java

script:
  - mvn clean verify
  - cd samples/spring-security-basic-auth
  - mvn clean verify
  - cd ../../samples/spring-security-xsuaa-usage
  - mvn clean verify
  - cd ../../samples/spring-webflux-security-xsuaa-usage
  - mvn clean verify
  - cd ../../samples/java-security-usage
  - mvn clean verify
